config/routes.rb
Rails.application.routes.draw do
  
  
  get 'sessions/new'
  resources :users
  resources :drills
  get '/pitching', to: 'gc_baseball#pitching'
  get '/hitting', to: 'gc_baseball#hitting'
  get '/strength', to: 'gc_baseball#strength'
  get '/add_drill', to: 'drills#new'
  get '/add_user', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'gc_baseball#home'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drill.rb
class Drill < ApplicationRecord
     has_and_belongs_to_many :player
     
    def print_drill
        return "#{name} sets: #{sets} reps: #{reps}  desc:#{description}"
    end
    
    def print_drill_list
        return "#{name} sets: #{sets} reps: #{reps}"
    end
        
end

app/models/user.rb
class User < ApplicationRecord
    has_and_belongs_to_many :drill
    
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
                    
    has_secure_password
    validates :password, presence: true, length: { minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drills_controller.rb
class DrillsController < ApplicationController
   
   def show
      @drill = Drill.find(params[:id])
   end
   
   def index
   end
   
   def new
       @drill = Drill.new
   end
   
   def create
     @drill = Drill.create(drill_params)
     if @drill.save
        redirect_to @drill
     else
        render 'new'
     end
   end
   
   private

    def drill_params
      params.permit(:sets, :name, :performance, :reps, :description)
    end
  
  
end

app/controllers/gc_baseball_controller.rb
class GcBaseballController < ApplicationController

  def setup
    @base_title = "Ruby on Rails Tutorial Sample App"
  end
  
  def pitching
    drills = Drill.all
    @pitching = drills.find_all {|a| a.performance == 'pitching'}
  end

  def hitting
    drills = Drill.all
    @hitting = drills.find_all {|a| a.performance == 'hitting'}
  end

  def strength
     drills = Drill.all
    @strength = drills.find_all {|a| a.performance == 'Strength'}
  end

  def home
    names = ["Alex Lavery", "Ryan Moeller", "Ryan Chang", "Nate Lu", "Justin Williams", "Lambo"]
    @featured_player = names.shuffle.first
    
    
    videos = ["https://www.youtube.com/embed/xjwafWDJSvU", "https://www.youtube.com/embed/pmPEdH2k3vM", "https://www.youtube.com/embed/1aMnVhOAXgg", "https://www.youtube.com/embed/5EMIfbIXkLg"]
    @tube = videos.shuffle.first
  end
  

  
  def vid
  end
  

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  
  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def show
    @user = User.find(params[:id])
    drills = Drill.all
    @pitching = drills.find_all {|a| a.performance == 'pitching'}
    @hitting = drills.find_all {|a| a.performance == 'hitting'}
    @strength = drills.find_all {|a| a.performance == 'Strength'}
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/drills_helper.rb
module DrillsHelper
end

app/helpers/gc_baseball_helper.rb
module GcBaseballHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
    session[:user_id] = user.id
    end
    
    def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
    end
    
    def logged_in?
    !current_user.nil?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drills/drillform.html.erb
<% provide(:title, "New Drill") %>
<h1>GcBaseball Add Drill</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @drill, local: true) do |f| %>
      <%= f.label :performance %>
      <%= f.text_field :performance %>
      
       <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :sets %>
      <%= f.text_field :sets %>

      <%= f.label :reps %>
      <%= f.text_field :reps %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.submit "Create Drill", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/drills/new.html.erb
<% provide(:title, "New Drill") %>
<h1>GcBaseball Add Drill</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @drill, local: true) do |f| %>
      <%= f.label :performance %>
      <%= f.text_field :performance %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :sets %>
      <%= f.text_field :sets %>

      <%= f.label :reps %>
      <%= f.text_field :reps %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.submit "Create Drill", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/drills/show.html.erb
<h1>New Drill</h1>
<center> <%= @drill.name %>, <%= @drill.performance %> </center>

app/views/gc_baseball/hitting.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
<% provide(:title, "Hitting") %>
<h1>GcBaseball Hitting</h1>

<p>Here we have the list of all Hitting drills we may perscribe. If you click on each drill, you will be able to see a short description of each drill. A majority of
these drills are utilized by Driveline Baseball, but many people use them. If interested in following their programming, or getting more information, check out their YouTube channel for more information.</p>
<div class="panel-group" id="accordion">
    <% @hitting.each_with_index do |drill, index| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a id="heading<%= index+1 %>" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index+1 %>" >
              <%= drill.name %> 
            </a>
          </h4>
        </div>
        <div id="collapse<%= index+1 %>" data-parent="#heading<%= index+1 %>" class="panel-collapse collapse">
          <div class="panel-body">
            <%= drill.description %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</p>

app/views/gc_baseball/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to Grinnell Baseball</h1>

  <h2>
    This page is meant to serve as a fall planning resource for virtual practice. Included in each page is a description of excercises in which we aim to be able to perform.
    Read the descriptions on each page for more information. When you sign up, you are displayed a sample daily workout.
  </h2>

  <%= link_to "Add Player", '#sign_up', class: "btn btn-lg btn-primary" %>
</div>
<h3> Featured Player </h3>
<p> <%= @featured_player %></p>
<h3> Featured Highlight Video made by Tim Hollibaugh</h3>
<iframe width="560" height="315" src="<%= @tube %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

app/views/gc_baseball/pitching.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
<% provide(:title, "Pitching") %>
<h1>GcBaseball Pitching</h1>

<p>Here we have the list of all pitching drills we may perscribe. If you click on each drill, you will be able to see a short description of each drill. A majority of
these drills were created by Driveline Baseball, and utilize their PlyoCare balls. If interested in following their programming, check out their YouTube channel for more information.</p>
<div class="panel-group" id="accordion">
    <% @pitching.each_with_index do |drill, index| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a id="heading<%= index+1 %>" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index+1 %>" >
              <%= drill.name %> 
            </a>
          </h4>
        </div>
        <div id="collapse<%= index+1 %>" data-parent="#heading<%= index+1 %>" class="panel-collapse collapse">
          <div class="panel-body">
            <%= drill.description %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</p>

app/views/gc_baseball/strength.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
<% provide(:title, "Strength") %>
<h1>GcBaseball#strength</h1>
<p>Here we have the list of all Strength drills we may perscribe. If you click on each drill, you will be able to see a short description of each drill. One great resource for learning proper technique while lifting is 
Alan Thrall on Youtube. Check out their YouTube channel for more information, and helpful video to get you started.</p>
<div class="panel-group" id="accordion">
    <% @strength.each_with_index do |drill, index| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a id="heading<%= index+1 %>" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index+1 %>" >
              <%= drill.name %> 
            </a>
          </h4>
        </div>
        <div id="collapse<%= index+1 %>" data-parent="#heading<%= index+1 %>" class="panel-collapse collapse">
          <div class="panel-body">
            <%= drill.description %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</p>

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Home", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Pitching",     pitching_path %></li>
        <li><%= link_to "Hitting",      hitting_path %></li>
        <li><%= link_to "Strength",     strength_path %></li>
        <li><%= link_to "Add Drill",    add_drill_path %></li>
        <li><%= link_to "Sign Up",      add_user_path %></li>
        <li><%= link_to "Log In",       login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Grinnell Baseball</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><center>Welcome</center></h1>
<div
<center> <%= @user.name %>, <%= @user.email %></center> 

</div>

<div>
    <center><h1>Heres a workout for you to do today.</h1></center>
    <h2><center>Throwing</center></h2>
    
    <% @pitching.each do | pitch | %>
    
    <li><%= pitch.print_drill_list %></li> <% end %>
    
    <h2><center>Hitting</center></h2>
    
    <% @hitting.each do | hit | %>
    
    <li><%= hit.print_drill_list %></li><% end %>
    
    <h2><center>Lifting</center></h2>
    
    <% @strength.each do | strength | %>
    
    <li><%= strength.print_drill_list %></li><% end %>
    
</div>